# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LocationDemo' do
pod 'Alamofire', '3.2'
end

target 'LocationDemoTests' do

end

target 'LocationDemoUITests' do

end

