# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'LoginAndRegister' do
pod 'SnapKit', '~> 0.15.0'
end

target 'LoginAndRegisterTests' do

end

target 'LoginAndRegisterUITests' do

end

